### ISSUE TITLE
persistent variables的支持有问题

### ISSUE THREAD

**Issue by LittleNightmare** [pipirapira/triggernometry-pro#2]
原版新增的persistent variables似乎都不能用（[1.1.4.1](https://github.com/paissaheavyindustries/Triggernometry/wiki/Triggernometry-changelog#1141)的支持了咩？

**Comment by pipirapira** [comment]
感谢反馈，兼容1.1.4.1所有功能的对应版本1.1.4.5已发布，请尽快更新。如有问题欢迎进一步反馈。
https://github.com/pipirapira/triggernometry-pro/releases/download/1.1.4.5/Triggernometry.dll

**Comment by LittleNightmare** [comment]
暂时莫得了
